name: Block node_modules
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run vendor guard
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/check-no-vendor.ps1
