# === AI‑ORCH HEADER ===
# File: .github/workflows/ci.yml
# Purpose: Basic CI to enforce format/lint/tests/security on PRs.
# Notes: Requires repo to be on GitHub.
name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Formatting (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Tests (pytest)
        run: pytest -q

      - name: Security (bandit)
        run: bandit -q -r .