name: CI
on:
  push:
  pull_request:

jobs:
  test:
    # Only run if this repo looks like Python
    if: >
      !cancelled() &&
      (
        hashFiles('requirements.txt') != '' ||
        hashFiles('pyproject.toml')  != ''  ||
        hashFiles('**/*.py')         != ''
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install deps (requirements.txt)
        if: hashFiles('requirements.txt') != ''
        run: python -m pip install -r requirements.txt

      # Ruff only if we have config or python files
      - name: Ruff
        if: >
          hashFiles('pyproject.toml')  != '' ||
          hashFiles('ruff.toml')       != '' ||
          hashFiles('**/*.py')         != ''
        run: |
          python -m pip install ruff
          python -m ruff check .

      # Mypy only if config or python files are present
      - name: Mypy (soft fail while stabilizing)
        if: >
          hashFiles('mypy.ini')        != '' ||
          hashFiles('setup.cfg')       != '' ||
          hashFiles('pyproject.toml')  != '' ||
          hashFiles('**/*.py')         != ''
        run: |
          python -m pip install mypy types-requests
          # Use --ignore-missing-imports for now to keep CI green
          python -m mypy app core tools --ignore-missing-imports || echo "mypy soft fail (ignored)"

      # Pytest only if there are tests or config
      - name: Pytest
        if: >
          hashFiles('pytest.ini')      != '' ||
          hashFiles('pyproject.toml')  != '' ||
          hashFiles('**/tests/**')     != '' ||
          hashFiles('**/test_*.py')    != '' ||
          hashFiles('**/*_test.py')    != ''
        run: |
          python -m pip install pytest
          python -m pytest -q
