name: Convert PR Dry-Run
on:
  pull_request:
    branches: [ "main" ]

jobs:
  dryrun:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server (background)
        env:
          HOST: 127.0.0.1
          PORT: 8121
          REPORTS_DIR: reports
          LOG_LEVEL: INFO
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          XAI_API_KEY:     ${{ secrets.XAI_API_KEY }}
        run: |
          python -m uvicorn --factory app.server:create_app --host 127.0.0.1 --port 8121 &
          echo $! > uvicorn.pid
          sleep 2
          curl -sSf http://127.0.0.1:8121/readyz

      - name: Dry-run convert on diff
        id: convert
        env:
          GH_PR_NUMBER: ${{ github.event.number }}
          GH_BASE_SHA:  ${{ github.event.pull_request.base.sha }}
        run: |
          BODY=$(jq -n \
            --arg root "src" \
            --argjson dry_run true \
            --arg label "pr-${GH_PR_NUMBER}" \
            --arg base "${GH_BASE_SHA}" \
            --argjson cap 25 \
            '{root:$root,dry_run:$dry_run,label:$label,git_diff_base:$base,batch_cap:$cap}')
          curl -sS -X POST "http://127.0.0.1:8121/convert/tree" \
            -H "Content-Type: application/json" \
            -d "${BODY}" | tee convert_resp.json
          SUMMARY=$(curl -sS "http://127.0.0.1:8121/reports/latest?label=pr-${GH_PR_NUMBER}" | jq -r '.path // ""')
          echo "path=${SUMMARY}" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH_LINE="${{ steps.convert.outputs.path }}"
          if [ -z "$PATH_LINE" ] || [ "$PATH_LINE" = "null" ]; then
            gh pr comment ${{ github.event.number }} --body "convert/tree dry-run completed, but no summary was found."
          else
            gh pr comment ${{ github.event.number }} --body "Review summary: \`$PATH_LINE\`"
          fi

      - name: Stop server
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi
