name: Frontend Gates

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-gates.yml'
  push:
    branches: ['*']
    paths:
      - 'frontend/**'

jobs:
  gates:
    # Run only if a real frontend project exists in this repo
    if: ${{ hashFiles('frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    concurrency:
      group: frontend-gates-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test:ci --if-present || npm run test --if-present -- -r

      - name: Lint
        run: npm run lint --if-present
