name: TS Migration Gates

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  gates:
    # Run only if this repo actually has TS + package.json
    if: >
      github.event_name != 'schedule' &&
      !cancelled() &&
      (
        (hashFiles('tsconfig.json') != '' || hashFiles('**/*.ts') != '' || hashFiles('**/*.tsx') != '') &&
        hashFiles('package.json') != ''
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # If there's no lockfile, npm ci fails; fall back to npm i
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: No-JS/JSX gate (PowerShell)
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/check-no-js.ps1

      - name: Type check (no emit)
        run: npx tsc --noEmit
